version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-bot
    environment:
      - DATABASE_URL=postgresql://postgres:hello@db:5432/inventory
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: inventory
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:

